### ISSUE TITLE
feature request: history of recently accessed results

### ISSUE THREAD

**Issue by silverhawke249** [Oppzippy/GlobalSearch#11]
i have a feature request: keybinds like ALT-UP/ALT-DOWN to browse thru history of recently accessed items -- e.g. after typing "wind rider" and using my mount, i'd like to be able to press the keybind to open the search box, then ALT-UP to select my mount, and then ENTER to use it.

would be a great QoL improvement if you can put this in! this addon is great :D

(p.s. in the search box help, you misspelled "previous" as "preivous")

**Comment by Oppzippy** [comment]
Added in 71955c682b574c50fc8f53ed6f21e344ca9a4ae4. Recent items display when the search is empty.
