### ISSUE TITLE
Taint due to category in keybinds?

### ISSUE THREAD

**Issue by tflo** [Oppzippy/GlobalSearch#13]
[Retail client 10.0.2]

Can you please double-check that you haven't introduced taint issues with your recent addition of a category to the keybindings?

In my tests, it taints.

I became aware of the Category taint issue when I was trying to do the same with my own addon today. Please see this [thread](https://us.forums.blizzard.com/en/wow/t/bindingsxml-taint-and-other-issues/1394681) for more info.

To reproduce:

1. Reload game client with all addons disabled, except GlobalSearch.
2. Open the Options Panel.
3. In the sidebar, click on Keybindings. (Important)
4. Exit the Options Panel.
5. You should get the taint dialog box now.
6. Do the same test without GlobalSearch loaded.

In case you can confirm the taint, you find a working solution in the (currently) last [post](https://us.forums.blizzard.com/en/wow/t/bindingsxml-taint-and-other-issues/1394681/9) of the aforementioned thread. 
For me, this did the trick.

– Tom

**Comment by Oppzippy** [comment]
Thanks for the detailed report. I went with the solution that you linked and the taint is fixed.

**Comment by tflo** [comment]
Thanks for fixing. Unfortunately, there are still quite a few addons out there that have fallen into the same trap. (More precisely: exactly _all_ addons I'm currently using and that have a category in bindings are producing taint ;)
