### ISSUE TITLE
Configurable frame strata

### ISSUE THREAD

**Issue by dodga** [Oppzippy/GlobalSearch#14]
It seems that the frames are below the Bartender 4 frames:

![frame-strata](https://user-images.githubusercontent.com/837105/205319867-34500a70-44fb-40f6-bcbd-681936f87176.png)

Is there a way to make the strata/layer configurable?
Alternatively, I believe having them on top of everything might be a sensible default :)

Thanks!

**Comment by Oppzippy** [comment]
I think the frame strata defaulted to medium before since it was never set. I added an option for it that defaults to DIALOG now.
