### ISSUE TITLE
Clear history (or remove individual items)

### ISSUE THREAD

**Issue by dodga** [Oppzippy/GlobalSearch#15]
Is there a way (keybinding, button in options?) to clear the history; even better: is there a keybinding to remove the currently select item from the history?

Thanks!

**Comment by Oppzippy** [comment]
I added a button to clear all history. Leaving the issue open until I add a way to remove specific items.

**Comment by Oppzippy** [comment]
Added in 3e224c11b5ab1ddb66a2ea15aec6ca1534d55d35. Right click a recent item, then Remove from Recent Items.
