### ISSUE TITLE
Font option only affects list but not hints

### ISSUE THREAD

**Issue by dodga** [Oppzippy/GlobalSearch#16]
It seems the font option only affects the items but not the hint(s) below:

![font](https://user-images.githubusercontent.com/837105/205320671-558e408d-d503-4f24-85df-69b0baf2079e.png)

I set "Myriad Condensed Web" in the options but it seems the hint ("Page 1 of 1") is still "Fritz Quadrata" (or whatever the default was).

While not critical, I think it would be nice if the font settings also affected that.

Also maybe a different request: maybe the hints could use a background to make them more readable, or having outlines without enabling outlines for the results?

Thanks!

**Comment by Oppzippy** [comment]
The help/page text font is fixed. Leaving this open until these are done:
- Make the text at the bottom more readable
- Add separate option for tooltip font, since the user may prefer different fonts for single lines of text compared to a paragraph

**Comment by Oppzippy** [comment]
> Also maybe a different request: maybe the hints could use a background to make them more readable, or having outlines without enabling outlines for the results?
I gave the help text its own font options with thin outlines enabled by default.
